Description of igmnBuilder
Home > igmn > igmnBuilder.m
igmnBuilder
PURPOSE
igmnBuilder - Incremental Gaussian Mixture Network Builder.
SYNOPSIS
function self = igmnBuilder(options) %#codegen
DESCRIPTION
 igmnBuilder - Incremental Gaussian Mixture Network Builder.
   self = igmnBuilder(options) creates a new instance of an Incremental
   Gaussian Mixture Network (IGMN) using the specified options.
   Inputs:
       options - An instance of the igmnoptions class that specifies
                 the configuration for the IGMN. If not provided, a
                 default igmnoptions instance is used.
   Outputs:
       self - A handle to the newly created IGMN instance.
   Example:
       opts = igmnoptions('MaxComponents', 10, 'LearningRate', 0.1);
       igmnInstance = igmnBuilder(opts);
   See also: igmnoptions, igmn
CROSS-REFERENCE INFORMATION
This function calls:
igmn IGMN Class
igmnoptions IGMNOPTIONS Class for configuring Incremental Gaussian Mixture Network (IGMN) options.
This function is called by:
compile compile - Compiles MATLAB functions into MEX or library files based on the specified problem configuration.
transpile transpile - Transpile MATLAB code to MEX functions using MATLAB Coder.
DOWNLOAD
igmnBuilder.m
SOURCE CODE
% igmnBuilder - Incremental Gaussian Mixture Network Builder.
%
%   self = igmnBuilder(options) creates a new instance of an Incremental
%   Gaussian Mixture Network (IGMN) using the specified options.
%
%   Inputs:
%       options - An instance of the igmnoptions class that specifies
%                 the configuration for the IGMN. If not provided, a
%                 default igmnoptions instance is used.
%
%   Outputs:
%       self - A handle to the newly created IGMN instance.
%
%   Example:
%       opts = igmnoptions('MaxComponents', 10, 'LearningRate', 0.1);
%       igmnInstance = igmnBuilder(opts);
%
%   See also: igmnoptions, igmn
function self = igmnBuilder(options) %#codegen
    arguments
        options (1, 1) {mustBeA(options, 'igmnoptions')} = igmnoptions();
    end
    self = igmn(options);
end