function net = resetState(net, compSize) %#codegen
    net = igmn(net.range, struct( ...
        'tau', net.tau, ...
        'delta', net.delta, ...
        'vMin', net.vMin, ...
        'spMin', net.spMin, ...
        'compSize', compSize));
end