function Y = classify(net, X, features)
    % CLASSIFY Classifies a given input.
    %   It returns a label-binarized vector where the predict class 
    %   have value.
    % Inputs:
    %   X : an NxM attributes array.
    % Output:
    %   y : an array label-binarized.
    arguments
        net (1, 1) igmn;
        X (:, :) { ...
            mustBeNumeric, ...
            mustBeNonempty ...
        };
        features (1, :) { ...
            mustBeNumeric, ...
            mustBeNonempty, ...
            mustBeInteger, ...
            mustBeNDimensional(net, X, features) ...
        } = [(size(X, 2) + 1):net.dimension];
    end
    Y = predict(net, X, features, 0);
    Y = Y == max(Y, [], 2);
end
