Description of mustBeNDimensional
Home > igmn > private > mustBeNDimensional.m
mustBeNDimensional
PURPOSE
mustBeNDimensional - Validate that input dimensions match the network's dimension
SYNOPSIS
function mustBeNDimensional(net, x, y)
DESCRIPTION
 mustBeNDimensional - Validate that input dimensions match the network's dimension
   mustBeNDimensional(net, x, y) checks if the combined dimensions of
   inputs `x` and `y` match the expected dimension specified in the
   `net.dimension` property. If the dimensions do not match, an error
   is thrown.
   mustBeNDimensional(net, x) checks if the dimensions of input `x`
   match the expected dimension specified in the `net.dimension`
   property. If the dimensions do not match, an error is thrown.
   Inputs:
       net - A structure or object containing the `dimension` property
             that specifies the expected dimensionality.
       x   - Input data array whose second dimension is considered.
       y   - (Optional) Additional input data array whose second
             dimension is considered.
   Throws:
       MException with identifier 'mustHaveSameDimension:notSameDimension'
       if the combined dimensions of `x` and `y` (or just `x` if `y` is
       not provided) do not match `net.dimension`.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
classify classify - Classifies a given input using the IGMN model.
clusterize crusterize - Computes the index of the component with the largest likelihood
learn learn - Learns a single training sample and updates the network.
predict predict - Classifies a given input and computes posterior probabilities.
recall recall - Performs the Gaussian Mixture Regression for a given input.
DOWNLOAD
mustBeNDimensional.m
SOURCE CODE
% mustBeNDimensional - Validate that input dimensions match the network's dimension
%
%   mustBeNDimensional(net, x, y) checks if the combined dimensions of
%   inputs `x` and `y` match the expected dimension specified in the
%   `net.dimension` property. If the dimensions do not match, an error
%   is thrown.
%
%   mustBeNDimensional(net, x) checks if the dimensions of input `x`
%   match the expected dimension specified in the `net.dimension`
%   property. If the dimensions do not match, an error is thrown.
%
%   Inputs:
%       net - A structure or object containing the `dimension` property
%             that specifies the expected dimensionality.
%       x   - Input data array whose second dimension is considered.
%       y   - (Optional) Additional input data array whose second
%             dimension is considered.
%
%   Throws:
%       MException with identifier 'mustHaveSameDimension:notSameDimension'
%       if the combined dimensions of `x` and `y` (or just `x` if `y` is
%       not provided) do not match `net.dimension`.
function mustBeNDimensional(net, x, y)
    coder.extrinsic('MException')
    coder.extrinsic('throwAsCaller')
    if nargin == 3
        D = size(x, 2) + size(y, 2);
    else
        D = size(x, 2);
    end
    if D ~= net.dimension
        eidType = 'mustHaveSameDimension:notSameDimension';
        msgType = 'Input must have the same dimension of data range';
        throwAsCaller(MException(eidType,msgType))
    end
end